apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: dailyfeed
type: Opaque
data:
  REDIS_PASSWORD: QWpjTHlTTE8zcXU2VFA0RQ==
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: infra
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
